### PR TITLE
Use `bluemonk/ipaddress` gem to validate IP address

### PR DESCRIPTION
**Pull request by dnswus**
Add support for IPv6.

### CODE REVIEW

**Comment by jeroenj** [comment]
Nice addition. Thanks. :+1: 

Could you rewrite it to use Ruby's [`Resolv::IPv4`](http://ruby-doc.org/stdlib-2.2.3/libdoc/resolv/rdoc/Resolv/IPv4.html) and [`Resolv::IPv6`](http://ruby-doc.org/stdlib-2.2.3/libdoc/resolv/rdoc/Resolv/IPv6.html) instead? I'd like to avoid adding an extra dependency for this.

Somethink like this should be okay:

```ruby
raise InvalidIpError.new(ip) unless ip.to_s =~ Resolv::IPv4::Regex || ip.to_s =~ Resolv::IPv6::Regex
```

Or you might want to take a look at [`IPAddr`](http://ruby-doc.org/stdlib-2.2.3/libdoc/ipaddr/rdoc/IPAddr.html). There is no `valid?` method or something like that, but initializing a new IP address that is not valid raises an exception. We could catch it and reraise it in the `InvalidIpAddress` or even skip that one completely.

**Comment by jeroenj** [comment]
You might also want to rebase this against master. I've pushed some other changes as well.

**Comment by dnswus** [comment]
@jeroenj rebased and rewritten using your approach. :smile:

**Comment by jeroenj** [comment]
Looks good! :+1: 

Could you just remove the version bump? I'll do it myself after its merged (and I'll release it to rubygems).

**Comment by dnswus** [comment]
@jeroenj reverted the version. :smile:

**Comment by jeroenj** [comment]
Thanks. I've released v0.6.0. :)

**Pull request merged**
